config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  #devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :articles
  #get 'articles/show/:id', to: 'articles#show'
  get 'show1', to: 'articles#show1'

  
  root 'welcome#index'
  
  mount Sidekiq::Web, at: "/sidekiq"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/background_job.rb
class BackgroundJob < ApplicationRecord
  belongs_to :user
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :background_jobs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Devise Stuff
  #before_filter :configure_permitted_parameters, if: :devise_controller?
  
   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :username) }
  end
  # End Devise Stuff
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  #before_filter :authenticate_user!, except: [:index, :show]
  
  def new
    @articles ||= Article.new 
  end
  
  
  def index
    #begin
      #raise RuntimeError.new("You messed up!")
    #  1/0
    #rescue => e
      #Rails.logger.error { "Encountered an error when trying to find or create Person for: , #{e.message} #{e.backtrace.join()}"}
      #Raven.capture_exception(e)
      #render json: { result: 'pending'}
      @item = current_user
      @articles = Article.all
      #render json: { result: 'pending'}
    #end
    
  end
  
  def create
    #render plain: params[:article].inspect
    #puts article_params.inspect
    @article = Article.new(article_params)
    #sleep(10)
    @article.save
    #h = {
    #:title => "New Article1", :text => "This is sample text"
    #}
    
    PygmentsWorker.perform_async
    GuestsCleanupJob.set(wait: 0.1.minute).perform_later(Article.find(14))
    redirect_to articles_path
    
  end
  
  def show
    #sleep(10)
    @article = Article.find(params[:id])
    #render json: { result: 'failure'}
    #render json: { result: 'pending'}
  end
  
  def show1
    #sleep(10)
    #@article = Article.find(params[:id])
    #render json: { result: 'failure'}
    @item = current_user
    render json: { result: 'pending'}
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<%-#= javascript_include_tag( 'sample1.js' ) -%>

<div id='loader'>
<%=image_tag("Eclipse-1s-200px.gif", alt: "Example Image", size: "50x50", display:"none")%>
</div>
<div id='status'>
<p> </p>
</div>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th><%= @item.email %></th>
  </tr>
  
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  
  <p>
    <%= form.submit "Create Article", :data => {:disable_with => 'Please Wait...', :confirm => "Are you sure?"} %>
  </p>
  
  <%= form.select :lists, [["test1", 1], ["test2", 0]] %>
  <%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    

      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>


    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= link_to 'My Blog', controller: 'articles' %>